config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :api do
    namespace :retailops do
      post 'catalog', to: 'catalog#catalog_push'
      post 'inventory', to: 'inventory#inventory_push'

      post 'orders', to: 'orders#index'
      post 'orders/mark_exported', to: 'orders#export'
      post 'orders/synchronize', to: 'orders#synchronize'
      post 'orders/add_packages', to: 'settlement#add_packages'
      post 'orders/mark_complete', to: 'settlement#mark_complete'
      post 'orders/add_refund', to: 'settlement#add_refund'
      post 'orders/payment_command', to: 'settlement#payment_command'
      post 'orders/cancel', to: 'settlement#cancel'
    end
  end

  #compat
  scope module: "api" do
    namespace :retailops do
      post 'catalog', to: 'catalog#catalog_push'
      post 'inventory', to: 'inventory#inventory_push'
    end
  end

  namespace :admin do
    resource :retailops_integration_settings, :only => ['update', 'edit']
  end

  namespace :api do
    put 'orders/:id/retailops_importable', to: 'orders#retailops_importable'
  end
end

app/controllers/spree/admin/retailops_integration_settings_controller.rb
module Spree
  module Admin
    class RetailopsIntegrationSettingsController < Spree::Admin::BaseController

      def update
        Spree::Config.set(params[:preferences])

        redirect_to edit_admin_retailops_integration_settings_path
      end
    end
  end
end

app/views/spree/admin/retailops_integration_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:retailops_integration_settings) %>
<% end %>

<%= form_tag admin_retailops_integration_settings_path, :method => :put do %>
  <div data-hook="default-import" class="field align-center">
    <%= preference_field_tag('preferences[retailops_import_by_default]', Spree::Config[:retailops_import_by_default], :type => :boolean) %>
    <%= label_tag nil, Spree.t(:retailops_import_by_default) %>
  </div>

  <div data-hook="ship-adj" class="field align-center">
    <%= label_tag nil, Spree.t(:retailops_express_shipping_price) %>
    <div class="choices">
      <ul>
        <li>
          <%= radio_button_tag 'preferences[retailops_express_shipping_price]', "adjustment", Spree::Config[:retailops_express_shipping_price] == "adjustment" %>
          <%= label_tag :preferences_retailops_express_shipping_price_adjustment, Spree.t(:retailops_standard_shipping_adjustment) %>
        </li>
        <li class="white-space-nowrap">
          <%= radio_button_tag 'preferences[retailops_express_shipping_price]', "cost", Spree::Config[:retailops_express_shipping_price] != "adjustment" %>
          <%= label_tag :preferences_retailops_express_shipping_price_cost, Spree.t(:retailops_first_cost) %>
        </li>
      </ul>
    </div>
  </div>

  <div class="form-buttons" data-hook="buttons">
    <%= button Spree.t('actions.update'), 'icon-refresh' %>
  </div>
<% end %>